name: chap-2-challenge
on: push
# 4 jobs that print the date
jobs:
  job1:
    name: Ubuntu
    runs-on: ubuntu-latest 
    steps:
      - name: step two
        run: date
  job2:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: step two
        run: date
  job3: 
      name: macOS
      runs-on: macos-latest
      steps:
        - name: step two
          run: date
  job4:
    name: Ubuntu-dependant
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - name: step two
        run: date
