name: Chap 4 Pipeline

on: push

env:
  APP: my-cool-app

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5.2.0

      - name: Install Requirements
        run: pip install --quiet --requirement ./Ch04/04_02/requirements.txt

      - name: Lint Code
        run: |
          flake8 --ignore=E501, E231 *.py
          pylint --disable=C0301 --disable=C0326 *.py

      - name: Run unit tests
        run: |
            python -m unittest --verbose --failfast