name: first

on: push # You can add conditions to run on specific branches or exclude branches etc. 

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v4 # Used to check out (download) the repository's code to the runner, which is the machine where the GitHub Actions workflow is being executed. By default, it checks out the repository at the commit that triggered the workflow, making the code available locally in the workflow environment. This is necessary if your workflow needs to run scripts, build, or test against the repository's code.
      - name: Step two
        run: env | sort

  job2: 
    needs: job1 # this adds a dependency to job 2, in this case job1 needs to finish successfully beofre job 2 can run (needs: [job1, job4] <this is the syntax adding more than one dependancy>)
    name: Second job
    runs-on: windows-latest
    steps: 
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name" # wrapped in quotes because the | might be interpreted as being part of the workflow
